---
- hosts: "{{ HOSTS | default('control[0]') }}"
  connection: local
  vars:
    #controller_hostname: "{{ hostvars[inventory_hostname].ansible_host }}"
    controller_hostname: "{{ lookup('env', 'TOWER_HOST') }}"
    controller_validate_certs: false

  tasks:
  - ansible.builtin.set_fact:
      environment_name_expanded: "Development"
    when: env == "Dev"

  - ansible.builtin.set_fact:
      environment_name_expanded: "QA"
    when: env == "QA"

  - ansible.builtin.set_fact:
      environment_name_expanded: "Production"
    when: env == "Prod"

  - name: Update EC2 Dynamic Inventory via source ==> "{{ content_view }} {{ environment_name_expanded }}"
    ansible.controller.inventory_source_update:
      name: "{{ content_view }} {{ environment_name_expanded }}"
      inventory: "EC2 Dynamic Inventory"
      organization: Default

  #- name: Update "ALL {{ environment_name_expanded }}" inventory via source ==> "EC2 Dynamic Source - {{ content_view }} {{ environment_name_expanded }} - ALL"
  #  ansible.controller.inventory_source_update:
  #    name: "EC2 Dynamic Source - {{ content_view }} {{ environment_name_expanded }} - ALL"
  #    inventory: "ALL {{ environment_name_expanded }}"
  #    organization: Default
