---
- name: Wait for connection...
  ansible.builtin.wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300

- name: Clearing yum cache...
  ansible.builtin.command: >-
    dnf clean all
...
