---
# https://devpress.csdn.net/cicd/62ec1d2689d9027116a10320.html
- name: Deploy satellite_infra workloads Task Group
  block:
  - name: Increment retry count
    set_fact:
      infra_subtasks_retry_count: "{{ 0 if infra_subtasks_retry_count is undefined else infra_subtasks_retry_count | int + 1 }}"
  - name: Resume failed Satellite tasks after each failed attempt
    ansible.builtin.include_tasks: satellite_hammer_task_resume.yml
    when: infra_subtasks_retry_count | int != 0

  - name: Execute redhat.satellite.content_credentials role
    ansible.builtin.import_role:
      name: "redhat.satellite.content_credentials"
    delegate_to: localhost

  - name: Execute redhat.satellite.repositories role
    ansible.builtin.import_role:
      name: "redhat.satellite.repositories"
    delegate_to: localhost

  - name: execute redhat.satellite.lifecycle_environments role
    ansible.builtin.import_role:
      name: "redhat.satellite.lifecycle_environments"
    delegate_to: localhost

  - name: execute content_views role
    ansible.builtin.import_role:
      name: "content_views"
    delegate_to: localhost

  - name: execute redhat.satellite.activation_keys role
    ansible.builtin.import_role:
      name: "redhat.satellite.activation_keys"
    delegate_to: localhost

  rescue:
    - fail:
        msg: Maximum retries of grouped tasks reached
      # initial try plus 3 retries = 4 total tries
      when: infra_subtasks_retry_count | int == 3

    - debug:
        msg: "satellite_infra workloads Task Group failed, retry count: {{ infra_subtasks_retry_count }}"

    - ansible.builtin.include_tasks: setup_satellite_infra_subtasks.yml
...