---
satellite_content_credentials:
  - name: RPM-GPG-KEY-foreman
    content_type: gpg_key
    content: "{{ lookup('url', 'https://yum.theforeman.org/releases/latest/RPM-GPG-KEY-foreman', split_lines=False) }}"
...
